config/routes.rb
Rails.application.routes.draw do
  
  resources :tag
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', sign_out: 'logout'},
   :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :articles
  resources :users

  resources :conversations, only: [:index, :show, :destroy] do
    member  do
      post :reply
      post :restore
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end  
      
  end
    
  resources :messages, only: [:new, :create]
  resources :calculators

  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  
  match "search", to: "static_pages#search", :via => [:get, :post]

  root 'static_pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base


	belongs_to :user
	validates :user_id, presence: true
	default_scope -> { order('updated_at DESC') }
	is_impressionable
	acts_as_taggable
	searchkick

	has_attached_file :avatar, 
	 	:styles => { 
	 		:medium => "300x300>",
	  		:thumb => "100x100>" }#,:default_url => "/images/:style/missing.png"

	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/  

	validates_presence_of :title, :store, :link, :content, :avatar	

	extend FriendlyId

	friendly_id :title, use: :slugged


	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  impressionist action: [:show]
  before_action :authenticate_user!, only: [ :new]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all#.order(updated_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @tags = Article.friendly.find(params[:id]).tag_counts_on(:tags)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :discount, :brand, :store, :link, :content, :expire_time, :timeZoneOffset, :created_by, :thumbnail_img, :avatar, :tag_list, :hasExpiryDate)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper

	def render_article_content(content)
		truncate(simple_format(content), :length => 100)
	end

	
		


end

app/views/articles/_form.html.erb
<script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>

<%= form_for @article, :html => { :multipart => true, :class => "form-horizontal", :role => "form" } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "* Title",  :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%#= f.cktext_area :title, :ckeditor => {:toolbar => 'mini'} %>
      <%= f.text_field :title, :class => "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :discount, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :discount, :class => "form-control" %>
    </div>  
  </div>
  

  <div class="form-group">
    <%= f.label "* Tags", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tag_list, :class => "form-control", :placeholder => "separated by commas" %>
    </div> 
  </div>
  
  <div class="form-group">
    <%= f.label :brand, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :brand, :class => "form-control"%>
    </div>   
  </div>


  <div class="form-group">
    <%= f.label "* Store", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :store, :class => "form-control" %>
    </div>   
  </div>

  <div class="form-group">
    <%= f.label "* link", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <% if @article.link.present? %>
        <%= f.text_field :link, :class => "form-control", :value => "#{@article.link}" %>
      <% else %>
        <%= f.text_field :link, :class => "form-control", :value => "http://" %>
      <% end %>
    </div>   
  </div>

  <div class="form-group">
    <%= f.label "* Content", :class => "col-sm-2 control-label" %><br><br>
    <%= f.cktext_area :content, :ckeditor => {:toolbar => 'mini', :height => '800'} %>
  </div>
  
  <div class="form-group">
    <%= f.check_box :hasExpiryDate %>exactly expiry date?
  </div>
  <div class="form-group expirydate_section hide">
    <%= f.label :expire_time, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :expire_time, :class => "form-control" %>
      <%#= f.select :timeZoneOffset, options_for_select([["PST", "8"], ["PDT", "7"],["EST", "5"], ["EDT", "4"]]), :selected => '3' %>
      <%= f.select :timeZoneOffset, options_for_select([["PST", "8"], ["PDT", "7"],["EST", "5"], ["EDT", "4"]], @article.timeZoneOffset  ) %>
    </div>   
  </div>
  

  <div class="form-group">

    <%= f.label :created_by, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%if @article.created_by.present? %>
        <%= f.text_field :created_by, :value => "#{@article.created_by}", :class => "form-control" %> 
      <% else %>
        <%= f.text_field :created_by, :value => "#{current_user.name}", :class => "form-control" %>
      <% end %>
      
    </div>   
  </div>


  <% if @article.avatar.present? %>
  <div class="form-group">
    <%= f.label " thumb image", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">

      <%= image_tag @article.avatar.url(:medium), :class => "form-control", :style => "width:200px; height:200px;" %>
    </div>   
  </div>
  <% end %>
  

  <div class="form-group">
    <%= f.label "* Avatar", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :avatar %>
    </div>  
  </div>

<br>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary btn-lg col-sm-6 col-sm-offset-3" %>
  </div>
<% end %>
<br>
<hr>


<script type="text/javascript">

  $('#article_hasExpiryDate').on( "click", function() {

    if($('#article_hasExpiryDate').prop('checked')) {
        $(".expirydate_section").removeClass('hide');
       
    } else {
        $(".expirydate_section").addClass('hide');
       
    }

  });

  var hasExpiryDate = <%= @article.hasExpiryDate %>;
  if (hasExpiryDate) {
    $(".expirydate_section").removeClass('hide');
    $('#article_hasExpiryDate').attr('checked')
       
  } else {
    $(".expirydate_section").addClass('hide');
  }

</script>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <%= current_user.email %>
  |
  <%= link_to "Change your password", edit_user_registration_path %>
  |
  <%= link_to "Users", users_path %>
  |
  <%= link_to "log out ", destroy_user_session_path, method: "delete" %>
  |

<%else%>
  not log in yet.  | <%= link_to "Log In ",new_user_session_path, method: "get" %> | <%= link_to "Sign Up ",new_user_registration_path, method: "get" %>
<%end%>

<h1>Listing articles</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Discount</th>
      <th>Tag</th>
      <th>Brand</th>
      <th>Store</th>
      <th>Cotent</th>
      <th>Expire time</th>
      <th>Created by</th>
      <th>View</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= image_tag article.avatar.url(:thumb) %></td>
        <td><%= link_to article.title, article %></td>
        <td><%= article.discount %></td>
        <td><%= article.tag_list %></td>
        <td><%= article.brand %></td>
        <td><%= link_to article.store, "#{article.link}", :target => "_blank" %></td>
        <td><%= render_article_content article.content %></td>
        <td><%= article.expire_time.to_s(:short) %></td>
        <td><%= article.created_by %></td>
        <td><%= article.impressionist_count %></td>
        <% if (current_user.try(:admin?) || current_user.id == article.user_id)  %>
          <td><%#= link_to 'Show', article %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% content_for :for_head do %>
  <meta property="og:title" content="<%= @article.discount %> <%= @article.title %>  @ <%= @article.store %>"  />
  <meta property="og:type" content="article" />
  <!--
  <meta property="og:description" content="<%#=raw truncate(@article.content, :length => 45) %> " />
  -->
  <meta property="og:url" content="http://www.dealsnail.com/articles/<%= @article.friendly_id %>" />
  <meta property="og:image" content="<%= @article.avatar.url(:medium) %>"/>
 
<% end %>


<div class="article-show">
  <%= link_to ' << Back', root_path %>

  <div class="row" style="margin-top:10px;">
    <div class="col-sm-2 " >
      <%= image_tag @article.avatar.url(:thumb), :class => "img-thumbnail" %>
    </div>
    <div class="col-sm-10">
      <div class="pull-right">
        <%if @article.hasExpiryDate %>
          <%= is_past_expire_time @article.expire_time, @article.timeZoneOffset %> 
        <% end %>  &nbsp;&nbsp;
        <%= render_view_number  @article.impressionist_count %>
          <%= fa_icon "lg eye", text: " : " %><%= @article.impressionist_count %>
        </span>  
      </div>

      <div class="pull-left">
        <h2>
        <%= is_past_discount @article.hasExpiryDate, @article.expire_time, @article.timeZoneOffset, @article.discount %>&nbsp;&nbsp; <span class="text-primary"><%= @article.title %></span>
        </h2>
      </div>  
      
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-sm-12" style="margin-bottom:10px;">
      <% if @article.brand.present? %>
        <strong>Brand: </strong><%= @article.brand %>&nbsp;&nbsp;
      <% end %>  

      <strong>Store: </strong><%= link_to @article.store, "#{@article.link}", :target => "_blank" %>
      <br><br>

      <% if @tags.present? %> 
        <%= fa_icon "lg tags", text: ":" %> <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
          <span class="label label-success"><%= link_to "# #{tag.name}", tag_path(tag), :class => css_class %></span>
        <% end %>
        &nbsp;&nbsp;
      <% end %>
      
      <div class="fb-like" data-href="http://www.dealsnail.com/articles/<%= @article.friendly_id %>" data-width="150" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
   
        

    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">

      <div class="well content-body">
        <%= raw @article.content %>
        <br>
        <div class="pull-right">
          post @<%= @article.updated_at.in_time_zone('Eastern Time (US & Canada)').to_s(:short)%> 
        </div>

      </div>
    </div>
  </div>

  <hr>
  <br>
  <div class="row">
  <div class="fb-comments" data-href="http://www.dealsnail.com/articles/<%= @article.friendly_id %>" data-numposts="5" data-colorscheme="light"></div>
  </div>
  <br>

</div>
  

<!-- for admin-->
<% if user_signed_in? %>
  <% if (current_user.try(:admin?) || current_user.id == @article.user_id)  %>
    <%= link_to 'Edit', edit_article_path(@article) %>
  <% end %>
<% end %>