config/routes.rb
Rails.application.routes.draw do
  
  resources :tag
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', sign_out: 'logout'},
   :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :articles
  resources :users

  resources :conversations, only: [:index, :show, :destroy] do
    member  do
      post :reply
      post :restore
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end  
      
  end
    
  resources :messages, only: [:new, :create]
  resources :calculators

  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  
  match "search", to: "static_pages#search", :via => [:get, :post]

  root 'static_pages#home'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!	
	before_action :get_mailbox
	before_action :get_conversation, except: [:index, :empty_trash]
	before_action :get_box, only: [:index]


	def index
		#@conversations = @mailbox.inbox
		#.paginate(page: params[:page].per_page: 10)
		if @box.eql? "inbox"
			@conversations = @mailbox.inbox	
        elsif @box.eql? "sent"
        	@conversations = @mailbox.sentbox	
       	elsif @box.eql? "trash" 
       		@conversations = @mailbox.trash
       	end
       	@conversations = @conversations.paginate(page: params[:page], per_page: 10)	

        	
	end

	def show
	end	

	def destroy
		@conversation.move_to_trash(current_user)
		flash[:success] = "This conversation was moved to trash"
		redirect_to conversations_path
	end	

	def restore
		@conversation.untrash(current_user)
  		flash[:success] = 'The conversation was restored.'
  		redirect_to conversations_path
	end	

	def empty_trash
		@mailbox.trash.each do |conversation|
			conversation.receipts_for(current_user).update_all(deleted: true)
		end	
		flash[:success] = "Your trash was cleaned"
		redirect_to conversations_path

	end	

	def reply
		current_user.reply_to_conversation(@conversation, params[:body])
		flash[:success] = "Reply sent"
		redirect_to conversation_path(@conversation)
	end	

	def mark_as_read
		@conversation.mark_as_read(current_user)
		flash[:success] = "the conversation was marked as read"
		redirect_to conversations_path
	end	


	
	private

	def get_mailbox	
		@mailbox ||= current_user.mailbox
	end

	def get_conversation
		@conversation ||= @mailbox.conversations.find(params[:id])
	end	

	def get_box
		if params[:box].blank? or !["inbox", "sent", "trash"].include?(params[:box])
			params[:box] = "inbox"
		end
		@box = params[:box]

	end
		
end

app/helpers/conversations_helper.rb
module ConversationsHelper

	def mailbox_section(title, current_box, opts = {})
	    opts[:class] = opts.fetch(:class, '')
	    opts[:class] += ' active' if title.downcase == current_box
	    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
	end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix <% if ! conversation.is_unread?(current_user) %> read_color <% end %>">
  <%= link_to conversation.subject, conversation_path(conversation) %>
 
  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      	<%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <%else %>
    	<%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>

     	<% if conversation.is_unread?(current_user) %>
      		<%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                  class: 'btn btn-xs btn-info', method: :post %>
    	<% end %>
    <% end %>
  </div>
 
  <p><%#= render 'conversations/conversation', conversation: conversation %></p>
 
 <% if @box == 'inbox' %>
 	From: <%= conversation.last_sender.name %>
<% elsif @box == 'sent' %>
	To: <%= conversation.recipients.first.name %> 	
 <% end %>
  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/index.html.erb
<%# page_header "Your Conversations" %>

<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>

 
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>
 
  <div class="col-sm-9">
  	<% if @box == 'trash' %>
		<p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></p>
	<% end %>
	
    <ul class="list-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>
 
    <%= will_paginate %>
  </div>
</div>
 
<%#= will_paginate %>

app/views/conversations/show.html.erb
<style type="text/css">
  .messages {
    max-height: 400px;
    overflow-y: auto;
    margin-bottom: 1em;
    margin-top: 1em;
  }
</style>

<%# page_header "Conversation" %>
 
<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>
 
  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <% message = receipt.message %>
      
        <%= message.sender.name %>
          says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
        <br>

        <%= message.body %>
        <br>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>