config/routes.rb
Rails.application.routes.draw do
  
  resources :tag
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', sign_out: 'logout'},
   :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :articles
  resources :users

  resources :conversations, only: [:index, :show, :destroy] do
    member  do
      post :reply
      post :restore
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end  
      
  end
    
  resources :messages, only: [:new, :create]
  resources :calculators

  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  
  match "search", to: "static_pages#search", :via => [:get, :post]

  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Dealsnail.com 2014
                </div>
            </div>
            <% if user_signed_in? %>
              <%= current_user.email %>
              |
              <%= link_to "user profile", edit_user_registration_path %>
              |
              <%= link_to "Post a new discount info", new_article_path %>
              |
              <%= link_to "articles", articles_path %>
              |
              <%= link_to "Users", users_path %>
              |
              <%= link_to "log out ", destroy_user_session_path, method: "delete" %>
              |

            <%else%>
              <%= link_to "Log In ",new_user_session_path, method: "get" %> | <%= link_to "Sign Up ",new_user_registration_path, method: "get" %>
            <%end%>
        </div>
    </footer>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>"> <%= image_tag("nail.png", size: "32", :class =>"img-circle", style: "margin-bottom:5px;") %><span class="purple"> DealsNail  釘好康</span><sub>Nail your deals here!</sub>
                <sup style="top:-12px;"><span class="label label-warning">Beta</span></sup></a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <!--
                    <li class="page-scroll">
                        <a href="#portfolio">Classification</a>
                    </li>
                    -->
                    <li class="page-scroll">
                        <%= form_tag search_path, :method => :post, :class => "navbar-form navbar-right",:role => "search", :id => "search_form" do %> 
                            
                            <div class="input-group">
                               <input name="query" type="text" class="form-control" placeholder="Search">
                               <div class="input-group-btn">
                                  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                               </div>
                            </div>    
                        <% end %>

                          

                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
  <% if content_for? :for_head %>
    <%= yield :for_head %>
  <% end %>		
  <meta charset="utf-8">
  <meta name="description" content="providing good deals for every shopaholic">
  <meta name="author" content="one of shopaholics">

  <link rel="shortcut icon" href="<%= asset_path('favicon.ico')%>" />	  
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no, minimal-ui">
  <meta name="fb:app_id" content="1502520630019110"/>
  <meta property="fb:admins" content="758238745" />
  <meta name="og:site_name" content="Dealsnail"/>
  
  <title>Dealsnail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



  <script type="text/javascript">
  	
  </script>





</head>




<script type="text/javascript">
	var CKEDITOR_BASEPATH = '/assets/ckeditor/';
</script>

<body>
  <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PTK6CK"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PTK6CK');</script>
<!-- End Google Tag Manager -->

	<div id="fb-root"></div>
	

	<%= render 'layouts/header' %>
	<div class="container main">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-56887304-1', 'auto');
	  ga('send', 'pageview');

	</script>

</body>
</html>

<script type="text/javascript">
// add responsive class to the images in ckeditor
  $( document ).ready(function() {
    $('.content-body img').attr({class:"img-responsive"});
  });

</script>